# Generated by Django 5.2.4 on 2025-12-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
